name: Build

on:
  push:
    tags-ignore:
      - '**'
  pull_request:

env:
  BUILD_CONFIGURATION: Release
  PLATFORM_CONFIGURATION: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add 'boost' for 'msbuild'
        id: install-boost
        uses: MarkusJx/install-boost@v2.4.5
        with:
          boost_version: 1.84.0
          boost_install_dir: C:\libs\
          platform_version: 2022
          arch: x86
          toolset: msvc
          link: static

      - name: Add 'msbuild' to PATH
        id: install-msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: ${{ env.PLATFORM_CONFIGURATION }}

      - name: Build (msbuild)
        id: build
        working-directory: ${{ github.workspace }}
        run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.PLATFORM_CONFIGURATION }} asuna-gmod.sln

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: "asuna-gmod.dll"
          path: "build/release/asuna-gmod.dll"
          retention-days: 3